name: Publish package to GitHub Packages

on: [workflow_dispatch]

#on:
#  release:
#    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Publish to GitHub Packages Repository
        run: gradle publishMavenJavaPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}